version: '3'
services:
  db.postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=nastasiia
      - POSTGRES_PASSWORD=SENy@122
      - POSTGRES_DB=nastasiia11
    ports:
      - "5432:5432"
