version: '3'
services:
  api.tickets:
    build: backend/tickets
    volumes:
      - ./backend/tickets/src:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api.tickets
    env_file:
      - .env

  api.gatway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  notifications.router:
    container_name: notifications.router
    build: ./notifications/notification_router
    volumes:
      - ./notifications/notification_router/src:/usr/src/app
    command: sh -c "npm install && npm start"
    env_file:
      - .env

  notifications.email:
    container_name: notifications.email
    build: ./notifications/email
    volumes:
      - ./notifications/email/src:/usr/src/app
    command: sh -c "npm install && npm start"
    env_file:
      - .env

  socket.jonny:
    build: ./notifications/websocket
    volumes:
      - ./notifications/websocket/src:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: socket.jonny
    environment:
      - SERVER_NAME=socket.jonny
      - SERVER_PORT=80
    env_file:
      - .env

  redis.sockets:
    image: 'redis:alpine'
    volumes:
      - './volumes/db/redis/sockets:/data'

  front.public:
    build: ./frontend/public
    volumes:
      - ./frontend/public:/usr/src/app
    command: sh -c "npm install && npm start"

  front.admin:
    build: ./frontend/admin
    volumes:
      - ./frontend/admin:/usr/src/app
    command: sh -c "npm install && npm start"
